apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: DEBUG
        image: nginx:1.21.6
        name: nginx
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 100m
            memory: 256M
          requests:
            cpu: 100m
            memory: 128M
      volumes:
      - configMap:
          items:
          - key: body
            path: index.html
          name: simple-app
        name: simple-app
